export const lang={
    English:{
        budget:'Balance',
        spendings:'Spendings',
        incomes:'Incomes',
        add:'add',
        value:'value',
        months:['january','february','march','april','may','june','july','august','september','october','november','december'],
        deleteConfirm:'Do you want to delete this category?',
        deleteTConfirm:'Do you want to delete this transaction?',
        yes:'yes',
        no:'no',
        analytics:'Analysis',
        monthsShort:['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'],
        categories:'Categories',
        payInstruments:'Payment Instruments',
        payments:{card:'cards',
        cash:'cash',
        crypto:'crypto'},
        transactions:'Transactions',
        settings:'Settings',
        currency:'Currency',
        language:'Language'
    },
    Русский:{
        budget:'Баланс',
        spendings:'Расходы',
        incomes:'Доходы',
        add:'добавить',
        value:'сумма',
        months:['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'],
        deleteConfirm:'Хотите удалить эту категорию?',
        deleteTConfirm:'Хотите удалить эту транзакцию?',
        yes:'да',
        no:'нет',
        analytics:'Анализ',
        monthsShort:['янв','февр','март','апр','май','июнь','июль','авг','сент','окт','нояб','дек'],
        categories:'Категории',
        payInstruments:'Средства платежа',
        payments:{card:'карты',
        cash:'наличные',
        crypto:'крипта'},
        transactions:'Транзакции',
        settings:'Настройки',
        currency:'Валюта',
        language:'Язык'
    },
    Español:{
        budget:'Balance',
        spendings:'Gastos',
        incomes:'Ingresos',
        add:'agregar',
        value:'valor',
        months:['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],
        deleteConfirm:'¿Quieres eliminar esta categoría?',
        deleteTConfirm:'¿Quieres eliminar esta transacción?',
        yes:'sí',
        no:'no',
        analytics:'Análisis',
        monthsShort:['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'],
        categories:'Categorias',
        payInstruments:'Instrumentos de pago',
        payments:{card:'tarjeta de pago',
        cash:'dinero',
        crypto:'cripto'},
        transactions:'Pagos',
        settings:'Ajustes',
        currency:'Divisa',
        language:'Idioma'
    }
}